In [ ]:
-- 1. Joins: Combines rows from two or more tables based on a related column.
SELECT employees.employee_id, employees.employee_name, departments.department_name
FROM employees
INNER JOIN departments ON employees.department_id = departments.department_id;

-- 2. Unions: Combines the result sets of two or more SELECT statements without duplicates.
SELECT employee_id, employee_name FROM sales_team
UNION
SELECT employee_id, employee_name FROM marketing_team;

-- 3. Case Statements: Adds conditional logic to the SELECT statement, creating a new result column.
SELECT
  order_id,
  order_date,
  CASE
    WHEN total_amount > 1000 THEN 'High Value'
    WHEN total_amount > 500 THEN 'Medium Value'
    ELSE 'Low Value'
  END AS order_category
FROM orders;

-- 4. Updating/Deleting Data: Modifies or removes data in a table based on specified conditions.
UPDATE products SET price = price * 1.1 WHERE category = 'Electronics';
DELETE FROM customers WHERE last_purchase_date < '2023-01-01';

-- 5. Partition By: Divides the result set into partitions to perform ranking, aggregation, or other operations.
SELECT
  employee_id,
  salary,
  department_id,
  RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) AS salary_rank
FROM employees;

-- 6. Data Types: Defines the type of data that a column can hold when creating a table.
CREATE TABLE students (
  student_id INT PRIMARY KEY,
  first_name VARCHAR(50),
  last_name VARCHAR(50),
  birth_date DATE
);

-- 7. Aliasing: Renames a table or column with a temporary name for the duration of a query.
SELECT first_name AS 'First Name', last_name AS 'Last Name' FROM students;

-- 8. Views: Creates a virtual table based on the result of a SELECT query for simplified querying.
CREATE VIEW high_value_orders AS
SELECT order_id, customer_id, total_amount
FROM orders
WHERE total_amount > 1000;

-- 9. Having Clause: Filters the results of a GROUP BY query based on aggregate function conditions.
SELECT department_id, AVG(salary) AS avg_salary
FROM employees
GROUP BY department_id
HAVING AVG(salary) > 50000;

-- 10. GetDate(): Returns the current date and time from the database server.
SELECT GETDATE() AS current_date_time;

-- 11. Primary vs Foreign Key: Establishes relationships between tables, ensuring data integrity.
CREATE TABLE customers (
  customer_id INT PRIMARY KEY,
  customer_name VARCHAR(255),
  last_purchase_date DATE
);

CREATE TABLE orders (
  order_id INT PRIMARY KEY,
  customer_id INT FOREIGN KEY REFERENCES customers(customer_id),
  order_date DATE,
  total_amount DECIMAL(10, 2)
);